server:
  servlet:
    context-path: /spring-security-oauth-server
  port: 9002
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestionMembre?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root


#spring.profiles.active=dev

#logging.level.org.springframework=DEBUG
